name: SircApp Web CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter config --enable-web
      - run: flutter pub get
      #     - run: flutter test
      - run: flutter build web --web-renderer html --release
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: web-build
          path: build/web
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: web-build
      - name: Display structure of build files
        run: ls -R
        working-directory: ./web
      - name: Deploy to GH Pages
        run: |
          cd build
          mkdir publish
          cd publish
          
          # configure git
          git config --global user.email jixiaoyong1995@gmail.com
          git config --global user.name jixiaoyong
          
          # clone the web branch from github, and delete all files in web branch
          git clone https://${{secrets.GH_DEPLOY}}@github.com/jixiaoyong/SircApp.git .
          git log -n 1 --pretty=format:"%h - %cn(%ce): %s" > ../last_commit.txt
          git checkout -b web origin/web
          
          # remove all files except .git
          shopt -s extglob
          rm -rfv !(".git")
          
          # copy the build files to the web branch
          cp -rf ../web/* .
          
          # commit and push
          git add --all
          
          # read commit message from ../last_commit.txt
          git commit -F ../last_commit.txt
          git push
